[FIX] fleet: prevent adding character in vehicle  model year
Currently an error occurs when a user adds a character in the
`Model Year` of fleet vehicles.

error: `ValueError: invalid literal for int() with base 10: '2016/2017'`

With the recently code change with [1], a 'char' widget was added in the field
'model_year' so it allows entering a character instead of an of an integer.

This commit removes the 'char' widget from the mode l'model_year'
so the user will allow entering only numbers.

[1] - https://github.com/odoo/odoo/commit/d69cb61b6c69a4110bc1af30323d5c8b8398129b

sentry-5667064353

closes odoo/odoo#175490

Signed-off-by: Bertrand Dossogne (bedo) <bedo@odoo.com>